import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "@/generated/prisma/client";
import { getPool } from "@/lib/pg";

/* Prisma ORM client over the same pooled Neon connection as pg.ts — one
   connection pool for the whole console. Prisma 7's generated client
   (src/generated/prisma, regenerated by `prisma generate`) requires a
   driver adapter, so the existing pg Pool is handed to PrismaPg. The
   instance is cached on globalThis so dev hot-reloads reuse the same
   client instead of opening a new one per reload. */

declare global {
  var __sadaPrisma: PrismaClient | undefined;
}

export const prisma: PrismaClient =
  globalThis.__sadaPrisma ?? new PrismaClient({ adapter: new PrismaPg(getPool()) });

if (process.env.NODE_ENV !== "production") {
  globalThis.__sadaPrisma = prisma;
}
