// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Prisma 7 does not auto-load env files: point dotenv at .env.local, where
// `neon env pull` writes DATABASE_URL (same source the Next.js app uses).
import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
